/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockUSDM } from "./MockUSDM";
export type { Xolat } from "./Xolat";
export type { Xopredict } from "./Xopredict";
