/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as xolatSol from "./Xolat.sol";
export type { xolatSol };
export type { MockUSDM } from "./MockUSDM";
export type { MockWitnetRandomness } from "./MockWitnetRandomness";
