/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockWitnetRandomnessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "estimateRandomizeFee"
      | "getRandomnessAfter"
      | "isRandomized"
      | "lastPayment"
      | "lastRandomizeBlock"
      | "random"
      | "randomize"
      | "requiredFee"
      | "setRandomValue"
      | "setRandomized"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "estimateRandomizeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomnessAfter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRandomized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastRandomizeBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "random",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "randomize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requiredFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRandomValue",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRandomized",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "estimateRandomizeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomnessAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRandomized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRandomizeBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "random", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "randomize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requiredFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRandomValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRandomized",
    data: BytesLike
  ): Result;
}

export interface MockWitnetRandomness extends BaseContract {
  connect(runner?: ContractRunner | null): MockWitnetRandomness;
  waitForDeployment(): Promise<this>;

  interface: MockWitnetRandomnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  estimateRandomizeFee: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getRandomnessAfter: TypedContractMethod<
    [blockNumber: BigNumberish],
    [string],
    "view"
  >;

  isRandomized: TypedContractMethod<
    [blockNumber: BigNumberish],
    [boolean],
    "view"
  >;

  lastPayment: TypedContractMethod<[], [bigint], "view">;

  lastRandomizeBlock: TypedContractMethod<[], [bigint], "view">;

  random: TypedContractMethod<
    [range: BigNumberish, nonce: BigNumberish, blockNumber: BigNumberish],
    [bigint],
    "view"
  >;

  randomize: TypedContractMethod<[], [bigint], "payable">;

  requiredFee: TypedContractMethod<[], [bigint], "view">;

  setRandomValue: TypedContractMethod<
    [blockNumber: BigNumberish, nonce: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRandomized: TypedContractMethod<
    [blockNumber: BigNumberish, seed: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "estimateRandomizeFee"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRandomnessAfter"
  ): TypedContractMethod<[blockNumber: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isRandomized"
  ): TypedContractMethod<[blockNumber: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPayment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastRandomizeBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "random"
  ): TypedContractMethod<
    [range: BigNumberish, nonce: BigNumberish, blockNumber: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "randomize"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "requiredFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRandomValue"
  ): TypedContractMethod<
    [blockNumber: BigNumberish, nonce: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRandomized"
  ): TypedContractMethod<
    [blockNumber: BigNumberish, seed: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
