/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface XopredictInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arenaCount"
      | "arenas"
      | "createArena"
      | "dailyBetTotal"
      | "joinArena"
      | "maxBetPerDay"
      | "maxBetPerTx"
      | "owner"
      | "pause"
      | "paused"
      | "pickCard"
      | "pickSoloCard"
      | "renounceOwnership"
      | "setMaxBet"
      | "startSoloGame"
      | "transferOwnership"
      | "unpause"
      | "usdm"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArenaCreated"
      | "CardPicked"
      | "OwnershipTransferred"
      | "Paused"
      | "PlayerJoined"
      | "RoundRevealed"
      | "SoloPlayed"
      | "Unpaused"
      | "WinnerPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "arenaCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arenas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createArena",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyBetTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinArena",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxBetPerDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxBetPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pickCard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pickSoloCard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startSoloGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdm", values?: undefined): string;

  decodeFunctionResult(functionFragment: "arenaCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "arenas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyBetTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxBetPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxBetPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pickCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pickSoloCard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMaxBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startSoloGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdm", data: BytesLike): Result;
}

export namespace ArenaCreatedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    betAmount: BigNumberish,
    maxPlayers: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    betAmount: bigint,
    maxPlayers: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    betAmount: bigint;
    maxPlayers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardPickedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    cardIndex: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    player: string,
    cardIndex: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    cardIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [arenaId: BigNumberish, player: AddressLike];
  export type OutputTuple = [arenaId: bigint, player: string];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundRevealedEvent {
  export type InputTuple = [arenaId: BigNumberish, commitment: BytesLike];
  export type OutputTuple = [arenaId: bigint, commitment: string];
  export interface OutputObject {
    arenaId: bigint;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoloPlayedEvent {
  export type InputTuple = [
    player: AddressLike,
    betAmount: BigNumberish,
    cardIndex: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    betAmount: bigint,
    cardIndex: bigint
  ];
  export interface OutputObject {
    player: string;
    betAmount: bigint;
    cardIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerPaidEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [arenaId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    arenaId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Xopredict extends BaseContract {
  connect(runner?: ContractRunner | null): Xopredict;
  waitForDeployment(): Promise<this>;

  interface: XopredictInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arenaCount: TypedContractMethod<[], [bigint], "view">;

  arenas: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, string] & {
        betAmount: bigint;
        maxPlayers: bigint;
        playerCount: bigint;
        settled: boolean;
        winner: string;
      }
    ],
    "view"
  >;

  createArena: TypedContractMethod<
    [betAmount: BigNumberish, maxPlayers: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  dailyBetTotal: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  joinArena: TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;

  maxBetPerDay: TypedContractMethod<[], [bigint], "view">;

  maxBetPerTx: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pickCard: TypedContractMethod<
    [arenaId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  pickSoloCard: TypedContractMethod<
    [gameId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaxBet: TypedContractMethod<
    [perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;

  startSoloGame: TypedContractMethod<
    [betAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdm: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arenaCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arenas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, string] & {
        betAmount: bigint;
        maxPlayers: bigint;
        playerCount: bigint;
        settled: boolean;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createArena"
  ): TypedContractMethod<
    [betAmount: BigNumberish, maxPlayers: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dailyBetTotal"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "joinArena"
  ): TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "maxBetPerDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxBetPerTx"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pickCard"
  ): TypedContractMethod<
    [arenaId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pickSoloCard"
  ): TypedContractMethod<
    [gameId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxBet"
  ): TypedContractMethod<
    [perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startSoloGame"
  ): TypedContractMethod<[betAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdm"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ArenaCreated"
  ): TypedContractEvent<
    ArenaCreatedEvent.InputTuple,
    ArenaCreatedEvent.OutputTuple,
    ArenaCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CardPicked"
  ): TypedContractEvent<
    CardPickedEvent.InputTuple,
    CardPickedEvent.OutputTuple,
    CardPickedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "RoundRevealed"
  ): TypedContractEvent<
    RoundRevealedEvent.InputTuple,
    RoundRevealedEvent.OutputTuple,
    RoundRevealedEvent.OutputObject
  >;
  getEvent(
    key: "SoloPlayed"
  ): TypedContractEvent<
    SoloPlayedEvent.InputTuple,
    SoloPlayedEvent.OutputTuple,
    SoloPlayedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerPaid"
  ): TypedContractEvent<
    WinnerPaidEvent.InputTuple,
    WinnerPaidEvent.OutputTuple,
    WinnerPaidEvent.OutputObject
  >;

  filters: {
    "ArenaCreated(uint256,uint256,uint8)": TypedContractEvent<
      ArenaCreatedEvent.InputTuple,
      ArenaCreatedEvent.OutputTuple,
      ArenaCreatedEvent.OutputObject
    >;
    ArenaCreated: TypedContractEvent<
      ArenaCreatedEvent.InputTuple,
      ArenaCreatedEvent.OutputTuple,
      ArenaCreatedEvent.OutputObject
    >;

    "CardPicked(uint256,address,uint8)": TypedContractEvent<
      CardPickedEvent.InputTuple,
      CardPickedEvent.OutputTuple,
      CardPickedEvent.OutputObject
    >;
    CardPicked: TypedContractEvent<
      CardPickedEvent.InputTuple,
      CardPickedEvent.OutputTuple,
      CardPickedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlayerJoined(uint256,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "RoundRevealed(uint256,bytes32)": TypedContractEvent<
      RoundRevealedEvent.InputTuple,
      RoundRevealedEvent.OutputTuple,
      RoundRevealedEvent.OutputObject
    >;
    RoundRevealed: TypedContractEvent<
      RoundRevealedEvent.InputTuple,
      RoundRevealedEvent.OutputTuple,
      RoundRevealedEvent.OutputObject
    >;

    "SoloPlayed(address,uint256,uint8)": TypedContractEvent<
      SoloPlayedEvent.InputTuple,
      SoloPlayedEvent.OutputTuple,
      SoloPlayedEvent.OutputObject
    >;
    SoloPlayed: TypedContractEvent<
      SoloPlayedEvent.InputTuple,
      SoloPlayedEvent.OutputTuple,
      SoloPlayedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WinnerPaid(uint256,address,uint256)": TypedContractEvent<
      WinnerPaidEvent.InputTuple,
      WinnerPaidEvent.OutputTuple,
      WinnerPaidEvent.OutputObject
    >;
    WinnerPaid: TypedContractEvent<
      WinnerPaidEvent.InputTuple,
      WinnerPaidEvent.OutputTuple,
      WinnerPaidEvent.OutputObject
    >;
  };
}
