/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWitnetRandomness__factory } from "./IWitnetRandomness__factory";
export { Xolat__factory } from "./Xolat__factory";
