/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWitnetRandomness,
  IWitnetRandomnessInterface,
} from "../../../contracts/Xolat.sol/IWitnetRandomness";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gasPrice",
        type: "uint256",
      },
    ],
    name: "estimateRandomizeFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestBlock",
        type: "uint256",
      },
    ],
    name: "getRandomnessAfter",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestBlock",
        type: "uint256",
      },
    ],
    name: "isRandomized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "range",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "requestBlock",
        type: "uint256",
      },
    ],
    name: "random",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "randomize",
    outputs: [
      {
        internalType: "uint256",
        name: "requestBlock",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IWitnetRandomness__factory {
  static readonly abi = _abi;
  static createInterface(): IWitnetRandomnessInterface {
    return new Interface(_abi) as IWitnetRandomnessInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWitnetRandomness {
    return new Contract(address, _abi, runner) as unknown as IWitnetRandomness;
  }
}
