/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IWitnetRandomnessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "estimateRandomizeFee"
      | "getRandomnessAfter"
      | "isRandomized"
      | "random"
      | "randomize"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "estimateRandomizeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomnessAfter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRandomized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "random",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "randomize", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "estimateRandomizeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomnessAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRandomized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "random", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "randomize", data: BytesLike): Result;
}

export interface IWitnetRandomness extends BaseContract {
  connect(runner?: ContractRunner | null): IWitnetRandomness;
  waitForDeployment(): Promise<this>;

  interface: IWitnetRandomnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  estimateRandomizeFee: TypedContractMethod<
    [gasPrice: BigNumberish],
    [bigint],
    "view"
  >;

  getRandomnessAfter: TypedContractMethod<
    [requestBlock: BigNumberish],
    [string],
    "view"
  >;

  isRandomized: TypedContractMethod<
    [requestBlock: BigNumberish],
    [boolean],
    "view"
  >;

  random: TypedContractMethod<
    [range: BigNumberish, nonce: BigNumberish, requestBlock: BigNumberish],
    [bigint],
    "view"
  >;

  randomize: TypedContractMethod<[], [bigint], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "estimateRandomizeFee"
  ): TypedContractMethod<[gasPrice: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRandomnessAfter"
  ): TypedContractMethod<[requestBlock: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isRandomized"
  ): TypedContractMethod<[requestBlock: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "random"
  ): TypedContractMethod<
    [range: BigNumberish, nonce: BigNumberish, requestBlock: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "randomize"
  ): TypedContractMethod<[], [bigint], "payable">;

  filters: {};
}
