/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Xolat {
  export type PlayerStatsStruct = {
    totalWonUsdm: BigNumberish;
    totalPlayed: BigNumberish;
    dailyBetTotal: BigNumberish;
    lastBetDate: BigNumberish;
    rank: string;
    isBanned: boolean;
    recentLosses: BigNumberish;
    lastLossTime: BigNumberish;
  };

  export type PlayerStatsStructOutput = [
    totalWonUsdm: bigint,
    totalPlayed: bigint,
    dailyBetTotal: bigint,
    lastBetDate: bigint,
    rank: string,
    isBanned: boolean,
    recentLosses: bigint,
    lastLossTime: bigint
  ] & {
    totalWonUsdm: bigint;
    totalPlayed: bigint;
    dailyBetTotal: bigint;
    lastBetDate: bigint;
    rank: string;
    isBanned: boolean;
    recentLosses: bigint;
    lastLossTime: bigint;
  };

  export type RandomnessRequestStruct = {
    roundId: BigNumberish;
    requestBlock: BigNumberish;
    requestedAt: BigNumberish;
    celoPaid: BigNumberish;
    fulfilled: boolean;
  };

  export type RandomnessRequestStructOutput = [
    roundId: bigint,
    requestBlock: bigint,
    requestedAt: bigint,
    celoPaid: bigint,
    fulfilled: boolean
  ] & {
    roundId: bigint;
    requestBlock: bigint;
    requestedAt: bigint;
    celoPaid: bigint;
    fulfilled: boolean;
  };

  export type RoundStruct = {
    roundId: BigNumberish;
    roundType: string;
    player: AddressLike;
    arenaId: BigNumberish;
    commitHash: BytesLike;
    serverSeed: string;
    clientSeed: string;
    nonce: BigNumberish;
    randomness: BytesLike;
    numbers: BigNumberish[];
    winnerAddress: AddressLike;
    potUsdm: BigNumberish;
    txHash: string;
    selectedCard: BigNumberish;
    status: string;
    createdAt: BigNumberish;
  };

  export type RoundStructOutput = [
    roundId: bigint,
    roundType: string,
    player: string,
    arenaId: bigint,
    commitHash: string,
    serverSeed: string,
    clientSeed: string,
    nonce: bigint,
    randomness: string,
    numbers: bigint[],
    winnerAddress: string,
    potUsdm: bigint,
    txHash: string,
    selectedCard: bigint,
    status: string,
    createdAt: bigint
  ] & {
    roundId: bigint;
    roundType: string;
    player: string;
    arenaId: bigint;
    commitHash: string;
    serverSeed: string;
    clientSeed: string;
    nonce: bigint;
    randomness: string;
    numbers: bigint[];
    winnerAddress: string;
    potUsdm: bigint;
    txHash: string;
    selectedCard: bigint;
    status: string;
    createdAt: bigint;
  };
}

export interface XolatInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "RANDOMNESS_TIMEOUT"
      | "applyCooldown"
      | "arenaCount"
      | "arenas"
      | "ban"
      | "blacklist"
      | "checkRandomnessTimeout"
      | "cooldownDuration"
      | "createArena"
      | "dailyBetTotal"
      | "emergencyRefundRound"
      | "fetchRandomness"
      | "getArena"
      | "getCommitHash"
      | "getPlayerStats"
      | "getRandomness"
      | "getRandomnessRequest"
      | "getRound"
      | "isPlayerBanned"
      | "joinArena"
      | "lossesBeforeCooldown"
      | "maxBetPerDay"
      | "maxBetPerTx"
      | "owner"
      | "pause"
      | "paused"
      | "pickCard"
      | "pickSoloCard"
      | "playerStats"
      | "randomnessRequests"
      | "renounceOwnership"
      | "requestRandomness"
      | "revealSeeds"
      | "roundCount"
      | "rounds"
      | "setCooldownParams"
      | "setMaxBet"
      | "settleRound"
      | "startSoloGame"
      | "transferOwnership"
      | "unban"
      | "unpause"
      | "usdm"
      | "witnet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArenaCreated"
      | "CardPicked"
      | "CooldownApplied"
      | "OwnershipTransferred"
      | "Paused"
      | "PlayerBanned"
      | "PlayerJoined"
      | "RandomnessRequested"
      | "RandomnessRevealed"
      | "RandomnessTimeoutTriggered"
      | "RefundProcessed"
      | "RoundCreated"
      | "SeedRevealed"
      | "SoloPlayed"
      | "Unpaused"
      | "WinnerPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "RANDOMNESS_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyCooldown",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "arenaCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arenas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ban", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRandomnessTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createArena",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyBetTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRefundRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArena",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomnessRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlayerBanned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinArena",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lossesBeforeCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxBetPerDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxBetPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pickCard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pickSoloCard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "randomnessRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealSeeds",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roundCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownParams",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startSoloGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unban", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdm", values?: undefined): string;
  encodeFunctionData(functionFragment: "witnet", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "RANDOMNESS_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arenaCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "arenas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ban", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkRandomnessTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooldownDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyBetTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRefundRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommitHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomnessRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPlayerBanned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lossesBeforeCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxBetPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxBetPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pickCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pickSoloCard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomnessRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealSeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roundCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMaxBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startSoloGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unban", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "witnet", data: BytesLike): Result;
}

export namespace ArenaCreatedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    creator: AddressLike,
    betAmount: BigNumberish,
    maxPlayers: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    creator: string,
    betAmount: bigint,
    maxPlayers: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    creator: string;
    betAmount: bigint;
    maxPlayers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardPickedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    cardIndex: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    player: string,
    cardIndex: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    cardIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CooldownAppliedEvent {
  export type InputTuple = [player: AddressLike, duration: BigNumberish];
  export type OutputTuple = [player: string, duration: bigint];
  export interface OutputObject {
    player: string;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerBannedEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [arenaId: BigNumberish, player: AddressLike];
  export type OutputTuple = [arenaId: bigint, player: string];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessRequestedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    requestBlock: BigNumberish,
    requester: AddressLike,
    celoPaid: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    requestBlock: bigint,
    requester: string,
    celoPaid: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    requestBlock: bigint;
    requester: string;
    celoPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessRevealedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    commitHash: BytesLike,
    randomness: BytesLike
  ];
  export type OutputTuple = [
    roundId: bigint,
    commitHash: string,
    randomness: string
  ];
  export interface OutputObject {
    roundId: bigint;
    commitHash: string;
    randomness: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessTimeoutTriggeredEvent {
  export type InputTuple = [roundId: BigNumberish, requestBlock: BigNumberish];
  export type OutputTuple = [roundId: bigint, requestBlock: bigint];
  export interface OutputObject {
    roundId: bigint;
    requestBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    roundId: bigint,
    player: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    roundId: bigint;
    player: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundCreatedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    roundType: string,
    arenaId: BigNumberish,
    player: AddressLike,
    potUsdm: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    roundType: string,
    arenaId: bigint,
    player: string,
    potUsdm: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    roundType: string;
    arenaId: bigint;
    player: string;
    potUsdm: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeedRevealedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    serverSeed: string,
    clientSeed: string,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    serverSeed: string,
    clientSeed: string,
    nonce: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    serverSeed: string;
    clientSeed: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoloPlayedEvent {
  export type InputTuple = [
    player: AddressLike,
    betAmount: BigNumberish,
    cardIndex: BigNumberish,
    roundId: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    betAmount: bigint,
    cardIndex: bigint,
    roundId: bigint
  ];
  export interface OutputObject {
    player: string;
    betAmount: bigint;
    cardIndex: bigint;
    roundId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerPaidEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    winner: AddressLike,
    payout: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    roundId: bigint,
    winner: string,
    payout: bigint,
    reason: string
  ];
  export interface OutputObject {
    roundId: bigint;
    winner: string;
    payout: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Xolat extends BaseContract {
  connect(runner?: ContractRunner | null): Xolat;
  waitForDeployment(): Promise<this>;

  interface: XolatInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  RANDOMNESS_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  applyCooldown: TypedContractMethod<
    [player: AddressLike],
    [void],
    "nonpayable"
  >;

  arenaCount: TypedContractMethod<[], [bigint], "view">;

  arenas: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        arenaId: bigint;
        betAmount: bigint;
        maxPlayers: bigint;
        playerCount: bigint;
        settled: boolean;
        winner: string;
        createdAt: bigint;
        roundId: bigint;
        pickedCount: bigint;
      }
    ],
    "view"
  >;

  ban: TypedContractMethod<[player: AddressLike], [void], "nonpayable">;

  blacklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  checkRandomnessTimeout: TypedContractMethod<
    [roundId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cooldownDuration: TypedContractMethod<[], [bigint], "view">;

  createArena: TypedContractMethod<
    [betAmount: BigNumberish, maxPlayers: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  dailyBetTotal: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  emergencyRefundRound: TypedContractMethod<
    [roundId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fetchRandomness: TypedContractMethod<
    [roundId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getArena: TypedContractMethod<
    [arenaId: BigNumberish],
    [[bigint, bigint, bigint, bigint, boolean, string, bigint, string[]]],
    "view"
  >;

  getCommitHash: TypedContractMethod<[roundId: BigNumberish], [string], "view">;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [Xolat.PlayerStatsStructOutput],
    "view"
  >;

  getRandomness: TypedContractMethod<[roundId: BigNumberish], [string], "view">;

  getRandomnessRequest: TypedContractMethod<
    [roundId: BigNumberish],
    [Xolat.RandomnessRequestStructOutput],
    "view"
  >;

  getRound: TypedContractMethod<
    [roundId: BigNumberish],
    [Xolat.RoundStructOutput],
    "view"
  >;

  isPlayerBanned: TypedContractMethod<[player: AddressLike], [boolean], "view">;

  joinArena: TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;

  lossesBeforeCooldown: TypedContractMethod<[], [bigint], "view">;

  maxBetPerDay: TypedContractMethod<[], [bigint], "view">;

  maxBetPerTx: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pickCard: TypedContractMethod<
    [arenaId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  pickSoloCard: TypedContractMethod<
    [gameId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  playerStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string, boolean, bigint, bigint] & {
        totalWonUsdm: bigint;
        totalPlayed: bigint;
        dailyBetTotal: bigint;
        lastBetDate: bigint;
        rank: string;
        isBanned: boolean;
        recentLosses: bigint;
        lastLossTime: bigint;
      }
    ],
    "view"
  >;

  randomnessRequests: TypedContractMethod<
    [roundId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        roundId: bigint;
        requestBlock: bigint;
        requestedAt: bigint;
        celoPaid: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestRandomness: TypedContractMethod<
    [roundId: BigNumberish],
    [void],
    "payable"
  >;

  revealSeeds: TypedContractMethod<
    [
      roundId: BigNumberish,
      serverSeed: string,
      clientSeed: string,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  roundCount: TypedContractMethod<[], [bigint], "view">;

  rounds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        roundId: bigint;
        roundType: string;
        player: string;
        arenaId: bigint;
        commitHash: string;
        serverSeed: string;
        clientSeed: string;
        nonce: bigint;
        randomness: string;
        winnerAddress: string;
        potUsdm: bigint;
        txHash: string;
        selectedCard: bigint;
        status: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  setCooldownParams: TypedContractMethod<
    [duration: BigNumberish, losses: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxBet: TypedContractMethod<
    [perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleRound: TypedContractMethod<
    [roundId: BigNumberish],
    [void],
    "nonpayable"
  >;

  startSoloGame: TypedContractMethod<
    [betAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unban: TypedContractMethod<[player: AddressLike], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdm: TypedContractMethod<[], [string], "view">;

  witnet: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "RANDOMNESS_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "applyCooldown"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "arenaCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arenas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        arenaId: bigint;
        betAmount: bigint;
        maxPlayers: bigint;
        playerCount: bigint;
        settled: boolean;
        winner: string;
        createdAt: bigint;
        roundId: bigint;
        pickedCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ban"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkRandomnessTimeout"
  ): TypedContractMethod<[roundId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cooldownDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createArena"
  ): TypedContractMethod<
    [betAmount: BigNumberish, maxPlayers: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dailyBetTotal"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyRefundRound"
  ): TypedContractMethod<[roundId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fetchRandomness"
  ): TypedContractMethod<[roundId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getArena"
  ): TypedContractMethod<
    [arenaId: BigNumberish],
    [[bigint, bigint, bigint, bigint, boolean, string, bigint, string[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommitHash"
  ): TypedContractMethod<[roundId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [Xolat.PlayerStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRandomness"
  ): TypedContractMethod<[roundId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRandomnessRequest"
  ): TypedContractMethod<
    [roundId: BigNumberish],
    [Xolat.RandomnessRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRound"
  ): TypedContractMethod<
    [roundId: BigNumberish],
    [Xolat.RoundStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPlayerBanned"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "joinArena"
  ): TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lossesBeforeCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxBetPerDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxBetPerTx"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pickCard"
  ): TypedContractMethod<
    [arenaId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pickSoloCard"
  ): TypedContractMethod<
    [gameId: BigNumberish, cardIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "playerStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string, boolean, bigint, bigint] & {
        totalWonUsdm: bigint;
        totalPlayed: bigint;
        dailyBetTotal: bigint;
        lastBetDate: bigint;
        rank: string;
        isBanned: boolean;
        recentLosses: bigint;
        lastLossTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "randomnessRequests"
  ): TypedContractMethod<
    [roundId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        roundId: bigint;
        requestBlock: bigint;
        requestedAt: bigint;
        celoPaid: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRandomness"
  ): TypedContractMethod<[roundId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "revealSeeds"
  ): TypedContractMethod<
    [
      roundId: BigNumberish,
      serverSeed: string,
      clientSeed: string,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roundCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        roundId: bigint;
        roundType: string;
        player: string;
        arenaId: bigint;
        commitHash: string;
        serverSeed: string;
        clientSeed: string;
        nonce: bigint;
        randomness: string;
        winnerAddress: string;
        potUsdm: bigint;
        txHash: string;
        selectedCard: bigint;
        status: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCooldownParams"
  ): TypedContractMethod<
    [duration: BigNumberish, losses: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxBet"
  ): TypedContractMethod<
    [perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleRound"
  ): TypedContractMethod<[roundId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startSoloGame"
  ): TypedContractMethod<[betAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unban"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "witnet"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ArenaCreated"
  ): TypedContractEvent<
    ArenaCreatedEvent.InputTuple,
    ArenaCreatedEvent.OutputTuple,
    ArenaCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CardPicked"
  ): TypedContractEvent<
    CardPickedEvent.InputTuple,
    CardPickedEvent.OutputTuple,
    CardPickedEvent.OutputObject
  >;
  getEvent(
    key: "CooldownApplied"
  ): TypedContractEvent<
    CooldownAppliedEvent.InputTuple,
    CooldownAppliedEvent.OutputTuple,
    CooldownAppliedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerBanned"
  ): TypedContractEvent<
    PlayerBannedEvent.InputTuple,
    PlayerBannedEvent.OutputTuple,
    PlayerBannedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessRequested"
  ): TypedContractEvent<
    RandomnessRequestedEvent.InputTuple,
    RandomnessRequestedEvent.OutputTuple,
    RandomnessRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessRevealed"
  ): TypedContractEvent<
    RandomnessRevealedEvent.InputTuple,
    RandomnessRevealedEvent.OutputTuple,
    RandomnessRevealedEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessTimeoutTriggered"
  ): TypedContractEvent<
    RandomnessTimeoutTriggeredEvent.InputTuple,
    RandomnessTimeoutTriggeredEvent.OutputTuple,
    RandomnessTimeoutTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RoundCreated"
  ): TypedContractEvent<
    RoundCreatedEvent.InputTuple,
    RoundCreatedEvent.OutputTuple,
    RoundCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SeedRevealed"
  ): TypedContractEvent<
    SeedRevealedEvent.InputTuple,
    SeedRevealedEvent.OutputTuple,
    SeedRevealedEvent.OutputObject
  >;
  getEvent(
    key: "SoloPlayed"
  ): TypedContractEvent<
    SoloPlayedEvent.InputTuple,
    SoloPlayedEvent.OutputTuple,
    SoloPlayedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerPaid"
  ): TypedContractEvent<
    WinnerPaidEvent.InputTuple,
    WinnerPaidEvent.OutputTuple,
    WinnerPaidEvent.OutputObject
  >;

  filters: {
    "ArenaCreated(uint256,address,uint256,uint8)": TypedContractEvent<
      ArenaCreatedEvent.InputTuple,
      ArenaCreatedEvent.OutputTuple,
      ArenaCreatedEvent.OutputObject
    >;
    ArenaCreated: TypedContractEvent<
      ArenaCreatedEvent.InputTuple,
      ArenaCreatedEvent.OutputTuple,
      ArenaCreatedEvent.OutputObject
    >;

    "CardPicked(uint256,address,uint8)": TypedContractEvent<
      CardPickedEvent.InputTuple,
      CardPickedEvent.OutputTuple,
      CardPickedEvent.OutputObject
    >;
    CardPicked: TypedContractEvent<
      CardPickedEvent.InputTuple,
      CardPickedEvent.OutputTuple,
      CardPickedEvent.OutputObject
    >;

    "CooldownApplied(address,uint256)": TypedContractEvent<
      CooldownAppliedEvent.InputTuple,
      CooldownAppliedEvent.OutputTuple,
      CooldownAppliedEvent.OutputObject
    >;
    CooldownApplied: TypedContractEvent<
      CooldownAppliedEvent.InputTuple,
      CooldownAppliedEvent.OutputTuple,
      CooldownAppliedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlayerBanned(address)": TypedContractEvent<
      PlayerBannedEvent.InputTuple,
      PlayerBannedEvent.OutputTuple,
      PlayerBannedEvent.OutputObject
    >;
    PlayerBanned: TypedContractEvent<
      PlayerBannedEvent.InputTuple,
      PlayerBannedEvent.OutputTuple,
      PlayerBannedEvent.OutputObject
    >;

    "PlayerJoined(uint256,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "RandomnessRequested(uint256,uint256,address,uint256)": TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
    RandomnessRequested: TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;

    "RandomnessRevealed(uint256,bytes32,bytes32)": TypedContractEvent<
      RandomnessRevealedEvent.InputTuple,
      RandomnessRevealedEvent.OutputTuple,
      RandomnessRevealedEvent.OutputObject
    >;
    RandomnessRevealed: TypedContractEvent<
      RandomnessRevealedEvent.InputTuple,
      RandomnessRevealedEvent.OutputTuple,
      RandomnessRevealedEvent.OutputObject
    >;

    "RandomnessTimeoutTriggered(uint256,uint256)": TypedContractEvent<
      RandomnessTimeoutTriggeredEvent.InputTuple,
      RandomnessTimeoutTriggeredEvent.OutputTuple,
      RandomnessTimeoutTriggeredEvent.OutputObject
    >;
    RandomnessTimeoutTriggered: TypedContractEvent<
      RandomnessTimeoutTriggeredEvent.InputTuple,
      RandomnessTimeoutTriggeredEvent.OutputTuple,
      RandomnessTimeoutTriggeredEvent.OutputObject
    >;

    "RefundProcessed(uint256,address,uint256,string)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;

    "RoundCreated(uint256,string,uint256,address,uint256)": TypedContractEvent<
      RoundCreatedEvent.InputTuple,
      RoundCreatedEvent.OutputTuple,
      RoundCreatedEvent.OutputObject
    >;
    RoundCreated: TypedContractEvent<
      RoundCreatedEvent.InputTuple,
      RoundCreatedEvent.OutputTuple,
      RoundCreatedEvent.OutputObject
    >;

    "SeedRevealed(uint256,string,string,uint256)": TypedContractEvent<
      SeedRevealedEvent.InputTuple,
      SeedRevealedEvent.OutputTuple,
      SeedRevealedEvent.OutputObject
    >;
    SeedRevealed: TypedContractEvent<
      SeedRevealedEvent.InputTuple,
      SeedRevealedEvent.OutputTuple,
      SeedRevealedEvent.OutputObject
    >;

    "SoloPlayed(address,uint256,uint8,uint256)": TypedContractEvent<
      SoloPlayedEvent.InputTuple,
      SoloPlayedEvent.OutputTuple,
      SoloPlayedEvent.OutputObject
    >;
    SoloPlayed: TypedContractEvent<
      SoloPlayedEvent.InputTuple,
      SoloPlayedEvent.OutputTuple,
      SoloPlayedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WinnerPaid(uint256,address,uint256,string)": TypedContractEvent<
      WinnerPaidEvent.InputTuple,
      WinnerPaidEvent.OutputTuple,
      WinnerPaidEvent.OutputObject
    >;
    WinnerPaid: TypedContractEvent<
      WinnerPaidEvent.InputTuple,
      WinnerPaidEvent.OutputTuple,
      WinnerPaidEvent.OutputObject
    >;
  };
}
