/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as xolatSol from "./Xolat.sol";
export { MockUSDM__factory } from "./MockUSDM__factory";
export { MockWitnetRandomness__factory } from "./MockWitnetRandomness__factory";
