/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockUSDM__factory } from "./MockUSDM__factory";
export { Xolat__factory } from "./Xolat__factory";
export { Xopredict__factory } from "./Xopredict__factory";
